# Generated by Django 3.0.7 on 2020-08-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='description',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
    ]
